#!/usr/bin/env python3
"""
Debug script to test tool execution directly without the full dual model system.
This will help isolate whether the issue is in tool execution or response handling.
"""

import sys
from pathlib import Path

# Add the project root to Python path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

try:
    from models.session import CommandContext
    from services.tool_executor import ToolExecutor
    from services.gguf_tool_parser import GGUFToolCallParser
except ImportError as e:
    print(f"❌ Import error: {e}")
    print("Make sure you're running from the DeepCoderX directory")
    sys.exit(1)

def test_direct_tool_execution():
    """Test tool execution directly without dual model system."""
    print("🔧 Testing Direct Tool Execution")
    print("=" * 50)
    
    # Create a mock MCP client for testing
    class MockMCPClient:
        def read_file(self, path):
            return {"content": f"Mock content for {path}"}
        def write_file(self, path, content):
            return {"status": "success"}
        def list_dir(self, path):
            return {"result": {"files": ["file1.py", "file2.txt"], "directories": ["dir1"]}}
        def stat(self, path):
            return {"result": {"type": "file", "size": 100}}
        def move_file(self, source, dest, overwrite):
            return {"status": "success"}
        def mkdir(self, path, parents, exist_ok):
            return {"status": "success"}
    
    # Create a test context with correct constructor
    ctx = CommandContext(
        root_path=project_root,
        mcp_client=MockMCPClient(),
        sandbox_path=project_root,
        debug_mode=True
    )
    ctx.user_input = "test"  # Set user_input as attribute
    
    # Create tool executor
    tool_executor = ToolExecutor(ctx)
    
    # Test basic bash commands
    test_commands = [
        {"tool": "run_bash", "command": "pwd"},
        {"tool": "run_bash", "command": "ls"},
        {"tool": "run_bash", "command": "whoami"}
    ]
    
    for i, tool_call in enumerate(test_commands, 1):
        print(f"\n📝 Test {i}: {tool_call}")
        try:
            result = tool_executor.execute_tool(tool_call)
            print(f"✅ Result: {result}")
        except Exception as e:
            print(f"❌ Error: {e}")
    
    print("\n" + "=" * 50)

def test_tool_call_parsing():
    """Test tool call parsing."""
    print("🔍 Testing Tool Call Parsing")
    print("=" * 50)
    
    # Create parser
    parser = GGUFToolCallParser()
    
    # Test the exact format generated by the model
    test_responses = [
        '<tool_call>run_bash({"command": "pwd"})</tool_call>',
        '<tool_call>run_bash({"command": "ls"})</tool_call>',
        '<tool_call>run_bash({"command": "python -m pip install sortfiles"})</tool_call>'
    ]
    
    for i, response in enumerate(test_responses, 1):
        print(f"\n📝 Test {i}: {response}")
        try:
            tool_calls, clean_response = parser.parse_and_execute_format(response)
            print(f"✅ Parsed: {tool_calls}")
            print(f"📄 Clean response: '{clean_response}'")
        except Exception as e:
            print(f"❌ Error: {e}")
    
    print("\n" + "=" * 50)

def test_complete_pipeline():
    """Test the complete tool execution pipeline."""
    print("🔄 Testing Complete Pipeline")
    print("=" * 50)
    
    # Create mock MCP client
    class MockMCPClient:
        def read_file(self, path):
            return {"content": f"Mock content for {path}"}
        def write_file(self, path, content):
            return {"status": "success"}
        def list_dir(self, path):
            return {"result": {"files": ["file1.py"], "directories": []}}
    
    # Create context and components
    ctx = CommandContext(
        root_path=project_root,
        mcp_client=MockMCPClient(),
        sandbox_path=project_root,
        debug_mode=True
    )
    ctx.user_input = "test"  # Set user_input as attribute
    
    tool_executor = ToolExecutor(ctx)
    parser = GGUFToolCallParser()
    
    # Simulate what happens in dual model handler
    test_response = '<tool_call>run_bash({"command": "pwd"})</tool_call>'
    
    print(f"📝 Simulating response: {test_response}")
    
    # Parse tool calls
    tool_calls, clean_response = parser.parse_and_execute_format(test_response)
    print(f"✅ Parsed tool calls: {tool_calls}")
    
    # Execute tools
    tool_results = []
    for tool_call in tool_calls:
        try:
            result = tool_executor.execute_tool(tool_call)
            tool_results.append(result)
            print(f"✅ Tool result: {result}")
        except Exception as e:
            error_result = f"Tool execution error: {str(e)}"
            tool_results.append(error_result)
            print(f"❌ Tool error: {error_result}")
    
    # Simulate response setting (like in dual model handler)
    if tool_results:
        if len(tool_results) == 1:
            final_response = str(tool_results[0])
        else:
            formatted_results = []
            for i, result in enumerate(tool_results, 1):
                formatted_results.append(f"Result {i}: {result}")
            final_response = "\n".join(formatted_results)
        
        print(f"🎯 Final response would be: {final_response}")
    else:
        print("❌ No tool results - this is the problem!")
    
    print("\n" + "=" * 50)

if __name__ == "__main__":
    print("🚀 DeepCoderX Tool Execution Debug Test")
    print("=" * 60)
    
    try:
        test_direct_tool_execution()
        test_tool_call_parsing()
        test_complete_pipeline()
        
        print("\n🎉 Debug tests completed!")
        print("\n📋 Next steps:")
        print("1. Check if direct tool execution works")
        print("2. Check if parsing works")
        print("3. Check if complete pipeline produces a final response")
        print("\nIf all tests pass, the issue is in the dual model handler response handling.")
        
    except Exception as e:
        print(f"\n💥 Debug test failed: {e}")
        import traceback
        traceback.print_exc()
